SELECT ana.part_no                        part_no,
       ana.control_plan_no                control_plan_no,
       ana.ctrl_plan_revision_no          ctrl_plan_revision_no,
       ana.analysis_no                    analysis_no,
       ana.time_created                   time_created,
       Analysis_API.Get_Created_In(ana.analysis_no) created_in,
       Analysis_API.Finite_State_Decode__(ana.rowstate)      analysis_state,
       ana.rowstate                       analysis_state_db,
       an.data_point                      data_point,
       an.eng_drawing_ref                 eng_drawing_ref,
       an.test_operation_no               test_operation_no,
       an.test_operation_description      test_operation_description,
       an.qty_to_control                  qty_to_control,
       qs.result_no                       result_no,
       qs.result                          result,
       Qman_Result_Status_API.Decode(qs.result_status) result_status,
       qs.result_status                   result_status_db,
       qs.reported                        reported,
       qs.serial_no                       serial_no,
       qs.lot_batch_no                    lot_batch_no,
       an.outer_min                       outer_min,
       an.inner_min                       inner_min,
       an.norm_value                      norm_value,
       an.inner_max                       inner_max,
       an.outer_max                       outer_max,
       an.non_conform_qty                 non_conform_qty,
       an.number_outer_min                number_outer_min,
       an.number_inner_min                number_inner_min,
       an.number_outer_max                number_outer_max,
       an.number_inner_max                number_inner_max,
       an.number_norm_value               number_norm_value,
       ana.created_by                     created_by ,
       ANALYSIS_NORM_API.Finite_State_Decode__(an.rowstate) norm_status,
       an.rowstate                        norm_status_db,
       ana.order_no                       order_no,
       ana.line_no                        line_no,
       ana.release_no                     release_no,
       ana.receipt_no                     receipt_no,
       ana.vendor_no                      vendor_no,
       ana.sequence_no                    sequence_no,
       ana.work_center_no                 work_center_no,
       ana.lot_batch_no                   analysis_lot_batch_no,
       ana.production_line                production_line,
       ana.scheduled_date                 scheduled_date,
       ana.result                         analysis_result,
       an.norm_type                       norm_type,
       an.inspection_code                 inspection_code,
       qs.note_text                       note_text,
       qs.note_id                         note_id,
       an.last_activity_date              last_activity_date,
       Qman_Analysis_Result_State_API.Decode(ana.variable_result_status) variable_result_status,
       ana.time_confirmed                 time_confirmed,       
       ana.contract                       contract,
       ana.modified                       modified,
       ana.modified_date                  modified_date,
       an.reported_by                     reported_by,
       an.cancel_reason                   cancel_reason,
       qs.entered_by                      entered_by,
       qs.accuracy                        accuracy,
       ana.parent_analysis_no             parent_analysis_no,
       qs.tool_id                         tool_id,
       qs.tool_instance                   tool_instance,
       an.connected_tools                 connected_tools,
       an.media_required                  media_required_db,
       an.eval_meas_tech                  eval_meas_tech,
       an.sample_frequency                sample_frequency,
       an.process_character               process_character,
       an.product_character               product_character,
       an.special_char_class              special_char_class,
       an.method                          method,
       an.reaction_plan                   reaction_plan,
       an.machine_process_tool            machine_process_tool,
       an.acceptance_no                   acceptance_no,
       an.acceptance_sampling_status      acceptance_sampling_status,
       ana.rowtype                        Objtype,
       qs.rowid                           objid,
       TO_CHAR(qs.rowversion,'YYYYMMDDHH24MISS') objversion,
       an.rowstate                        objstate,
       ANALYSIS_NORM_API.Finite_State_Decode__(an.rowstate)               state,
       Analysis_Norm_API.Finite_State_Events__(an.rowstate)               objevents,
       qs.rowkey                         objkey
FROM   analysis_tab ana, analysis_norm_tab an, qman_sample_value_tab qs
WHERE  ana.analysis_no = an.analysis_no
AND    an.analysis_no = qs.analysis_no
AND    an.data_point = qs.data_point
AND    an.control_chart_type = 'VARIABLE'
AND    EXISTS (SELECT 1 FROM user_allowed_site_pub
               WHERE ana.contract = site)